### ISSUE TITLE
No way to obtain deepslate with Sky Void Additions

### ISSUE THREAD

**Issue by angelcaru** [BPR02/SkyBlock_Collection#34]
In the wiki it says that every item, mob, and advancement is obtainable but there seems to be no way to obtain deepslate with the datapack. Am I dumb or did you forget?

**Comment by BPR02** [comment]
The wiki needs some work, but deepslate can be obtained by throwing stone into a large magma cube via the Magma Cube Ore Conversions mechanic. An update is coming to make deepslate more accessible (#32), but it will probably be released after the 1.21.4 release comes out

**Comment by angelcaru** [comment]
Ah I see
